/* soapClient.c
   Generated by gSOAP 2.7.9e from ws/jms2webservice.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.9e 2007-04-13 14:25:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMsgFromTopic(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMsgFromTopic *ns1__getMsgFromTopic, struct _ns1__getMsgFromTopicResponse *ns1__getMsgFromTopicResponse)
{	struct __ns1__getMsgFromTopic soap_tmp___ns1__getMsgFromTopic;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8191/JMSService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getMsgFromTopic.ns1__getMsgFromTopic = ns1__getMsgFromTopic;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getMsgFromTopic(soap, &soap_tmp___ns1__getMsgFromTopic);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMsgFromTopic(soap, &soap_tmp___ns1__getMsgFromTopic, "-ns1:getMsgFromTopic", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMsgFromTopic(soap, &soap_tmp___ns1__getMsgFromTopic, "-ns1:getMsgFromTopic", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__getMsgFromTopicResponse(soap, ns1__getMsgFromTopicResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getMsgFromTopicResponse(soap, ns1__getMsgFromTopicResponse, "ns1:getMsgFromTopicResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__postMsgToTopic(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__postMsgToTopic *ns1__postMsgToTopic, struct _ns1__postMsgToTopicResponse *ns1__postMsgToTopicResponse)
{	struct __ns1__postMsgToTopic soap_tmp___ns1__postMsgToTopic;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8191/JMSService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__postMsgToTopic.ns1__postMsgToTopic = ns1__postMsgToTopic;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__postMsgToTopic(soap, &soap_tmp___ns1__postMsgToTopic);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__postMsgToTopic(soap, &soap_tmp___ns1__postMsgToTopic, "-ns1:postMsgToTopic", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__postMsgToTopic(soap, &soap_tmp___ns1__postMsgToTopic, "-ns1:postMsgToTopic", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__postMsgToTopicResponse(soap, ns1__postMsgToTopicResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__postMsgToTopicResponse(soap, ns1__postMsgToTopicResponse, "ns1:postMsgToTopicResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__postMsgToQueue(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__postMsgToQueue *ns1__postMsgToQueue, struct _ns1__postMsgToQueueResponse *ns1__postMsgToQueueResponse)
{	struct __ns1__postMsgToQueue soap_tmp___ns1__postMsgToQueue;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8191/JMSService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__postMsgToQueue.ns1__postMsgToQueue = ns1__postMsgToQueue;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__postMsgToQueue(soap, &soap_tmp___ns1__postMsgToQueue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__postMsgToQueue(soap, &soap_tmp___ns1__postMsgToQueue, "-ns1:postMsgToQueue", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__postMsgToQueue(soap, &soap_tmp___ns1__postMsgToQueue, "-ns1:postMsgToQueue", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__postMsgToQueueResponse(soap, ns1__postMsgToQueueResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__postMsgToQueueResponse(soap, ns1__postMsgToQueueResponse, "ns1:postMsgToQueueResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMsgFromQueue(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getMsgFromQueue *ns1__getMsgFromQueue, struct _ns1__getMsgFromQueueResponse *ns1__getMsgFromQueueResponse)
{	struct __ns1__getMsgFromQueue soap_tmp___ns1__getMsgFromQueue;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8191/JMSService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getMsgFromQueue.ns1__getMsgFromQueue = ns1__getMsgFromQueue;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getMsgFromQueue(soap, &soap_tmp___ns1__getMsgFromQueue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMsgFromQueue(soap, &soap_tmp___ns1__getMsgFromQueue, "-ns1:getMsgFromQueue", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMsgFromQueue(soap, &soap_tmp___ns1__getMsgFromQueue, "-ns1:getMsgFromQueue", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default__ns1__getMsgFromQueueResponse(soap, ns1__getMsgFromQueueResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getMsgFromQueueResponse(soap, ns1__getMsgFromQueueResponse, "ns1:getMsgFromQueueResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of soapClient.c */
