/* ws/jms2webservice.h
   Generated by wsdl2h 1.2.9e from http://localhost:8191/JMSService?wsdl and typemap.dat
   2007-04-13 14:25:50 GMT
   Copyright (C) 2001-2006 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * http://webservice.comm.ideais.sf.net                                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://webservice.comm.ideais.sf.net"
ns2 = "http://jms.javax"
ns3 = "http://util.java"
ns4 = "http://lang.java"
ns5 = "http://naming.javax"

*/

//gsoap ns1   schema namespace:	http://webservice.comm.ideais.sf.net
//gsoap ns2   schema namespace:	http://jms.javax
//gsoap ns3   schema namespace:	http://util.java
//gsoap ns4   schema namespace:	http://lang.java
//gsoap ns5   schema namespace:	http://naming.javax
//gsoap ns1   schema form:	qualified
//gsoap ns2   schema form:	qualified
//gsoap ns3   schema form:	qualified
//gsoap ns4   schema form:	qualified
//gsoap ns5   schema form:	qualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *options; /* NOTE: for DIME and MTOM XOP attachments only */
};

/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };



/// Element "http://webservice.comm.ideais.sf.net":getMsgFromTopic of complexType.

/// "http://webservice.comm.ideais.sf.net":getMsgFromTopic is a complexType.
struct _ns1__getMsgFromTopic
{
/// Element in0 of type xs:string.
    char*                                in0                            1;	///< Nullable pointer.
/// Element in1 of type xs:string.
    char*                                in1                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":getMsgFromTopicResponse of complexType.

/// "http://webservice.comm.ideais.sf.net":getMsgFromTopicResponse is a complexType.
struct _ns1__getMsgFromTopicResponse
{
/// Element out of type "http://jms.javax":ArrayOfTextMessage.
    struct ns2__ArrayOfTextMessage*      out                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":postMsgToTopic of complexType.

/// "http://webservice.comm.ideais.sf.net":postMsgToTopic is a complexType.
struct _ns1__postMsgToTopic
{
/// Element in0 of type xs:string.
    char*                                in0                            1;	///< Nullable pointer.
/// Element in1 of type xs:string.
    char*                                in1                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":postMsgToTopicResponse of complexType.

/// "http://webservice.comm.ideais.sf.net":postMsgToTopicResponse is a complexType.
struct _ns1__postMsgToTopicResponse
{
/// Element out of type "http://jms.javax":TextMessage.
    struct ns2__TextMessage*             out                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":postMsgToQueue of complexType.

/// "http://webservice.comm.ideais.sf.net":postMsgToQueue is a complexType.
struct _ns1__postMsgToQueue
{
/// Element in0 of type xs:string.
    char*                                in0                            1;	///< Nullable pointer.
/// Element in1 of type xs:string.
    char*                                in1                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":postMsgToQueueResponse of complexType.

/// "http://webservice.comm.ideais.sf.net":postMsgToQueueResponse is a complexType.
struct _ns1__postMsgToQueueResponse
{
/// Element out of type "http://jms.javax":TextMessage.
    struct ns2__TextMessage*             out                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":getMsgFromQueue of complexType.

/// "http://webservice.comm.ideais.sf.net":getMsgFromQueue is a complexType.
struct _ns1__getMsgFromQueue
{
/// Element in0 of type xs:string.
    char*                                in0                            1;	///< Nullable pointer.
};


/// Element "http://webservice.comm.ideais.sf.net":getMsgFromQueueResponse of complexType.

/// "http://webservice.comm.ideais.sf.net":getMsgFromQueueResponse is a complexType.
struct _ns1__getMsgFromQueueResponse
{
/// Element out of type "http://jms.javax":ArrayOfTextMessage.
    struct ns2__ArrayOfTextMessage*      out                            1;	///< Nullable pointer.
};

/// "http://jms.javax":ArrayOfTextMessage is a complexType.
struct ns2__ArrayOfTextMessage
{
/// Size of array of struct ns2__TextMessage* is 0..unbounded
    int                                  __sizeTextMessage             ;
/// Array of length 0..unbounded
    struct ns2__TextMessage*             TextMessage                    0;	///< Nullable pointer.
};

/// "http://jms.javax":TextMessage is a complexType.
struct ns2__TextMessage
{
/// Element text of type xs:string.
    char*                                text                           0;	///< Nullable pointer.
/// Element JMSCorrelationID of type xs:string.
    char*                                JMSCorrelationID               0;	///< Nullable pointer.
/// Element JMSCorrelationIDAsBytes of type xs:base64Binary.
    struct xsd__base64Binary*            JMSCorrelationIDAsBytes        0;	///< Nullable pointer.
/// Element JMSDeliveryMode of type xs:int.
    int*                                 JMSDeliveryMode                0;	///< Optional element.
/// Element JMSDestination of type "http://jms.javax":Destination.
    struct ns2__Destination*             JMSDestination                 0;	///< Nullable pointer.
/// Element JMSExpiration of type xs:long.
    LONG64*                              JMSExpiration                  0;	///< Optional element.
/// Element JMSMessageID of type xs:string.
    char*                                JMSMessageID                   0;	///< Nullable pointer.
/// Element JMSPriority of type xs:int.
    int*                                 JMSPriority                    0;	///< Optional element.
/// Element JMSRedelivered of type xs:boolean.
    enum xsd__boolean*                   JMSRedelivered                 0;	///< Optional element.
/// Element JMSReplyTo of type "http://jms.javax":Destination.
    struct ns2__Destination*             JMSReplyTo                     0;	///< Nullable pointer.
/// Element JMSTimestamp of type xs:long.
    LONG64*                              JMSTimestamp                   0;	///< Optional element.
/// Element JMSType of type xs:string.
    char*                                JMSType                        0;	///< Nullable pointer.
/// Element propertyNames of type "http://util.java":Enumeration.
    struct ns3__Enumeration*             propertyNames                  0;	///< Nullable pointer.
};

/// "http://jms.javax":Destination is a complexType.
struct ns2__Destination
{
};

/// "http://jms.javax":JMSException is a complexType.
struct ns2__JMSException
{
/// Element errorCode of type xs:string.
    char*                                errorCode                      0;	///< Nullable pointer.
/// Element linkedException of type "http://lang.java":Exception.
    struct ns4__Exception*               linkedException                0;	///< Nullable pointer.
};

/// "http://util.java":Enumeration is a complexType.
struct ns3__Enumeration
{
};

/// "http://lang.java":Exception is a complexType.
struct ns4__Exception
{
};

/// "http://lang.java":Throwable is a complexType.
struct ns4__Throwable
{
};

/// "http://naming.javax":NamingException is a complexType.
struct ns5__NamingException
{
/// Element cause of type "http://lang.java":Throwable.
    struct ns4__Throwable*               cause                          0;	///< Nullable pointer.
/// Element explanation of type xs:string.
    char*                                explanation                    0;	///< Nullable pointer.
/// Element remainingName of type "http://naming.javax":Name.
    struct ns5__Name*                    remainingName                  0;	///< Nullable pointer.
/// Element resolvedName of type "http://naming.javax":Name.
    struct ns5__Name*                    resolvedName                   0;	///< Nullable pointer.
/// Element resolvedObj of type xs:anyType.
    _XML                                 resolvedObj                    0;	///< Nullable pointer.
/// Element rootCause of type "http://lang.java":Throwable.
    struct ns4__Throwable*               rootCause                      0;	///< Nullable pointer.
};

/// "http://naming.javax":Name is a complexType.
struct ns5__Name
{
/// Element all of type "http://util.java":Enumeration.
    struct ns3__Enumeration*             all                            0;	///< Nullable pointer.
/// Element empty of type xs:boolean.
    enum xsd__boolean*                   empty                          0;	///< Optional element.
};

/// Element "http://webservice.comm.ideais.sf.net":JMSException of type "http://jms.javax":JMSException.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://webservice.comm.ideais.sf.net":NamingException of type "http://naming.javax":NamingException.
/// Note: use wsdl2h option -g to generate this global element declaration.

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	JMSServiceHttpBinding 
//gsoap ns1  service type:	JMSServicePortType 
//gsoap ns1  service port:	http://localhost:8191/JMSService 
//gsoap ns1  service namespace:	http://webservice.comm.ideais.sf.net 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref JMSServiceHttpBinding

*/

/**

@page JMSServiceHttpBinding Binding "JMSServiceHttpBinding"

@section JMSServiceHttpBinding_operations Operations of Binding  "JMSServiceHttpBinding"
  - @ref __ns1__getMsgFromTopic
  - @ref __ns1__postMsgToTopic
  - @ref __ns1__postMsgToQueue
  - @ref __ns1__getMsgFromQueue

@section JMSServiceHttpBinding_ports Endpoints of Binding  "JMSServiceHttpBinding"
  - http://localhost:8191/JMSService

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * SOAP Fault Detail                                                          *
 *                                                                            *
\******************************************************************************/

/**

The SOAP Fault is part of the gSOAP context and its content is accessed
through the soap.fault->detail variable (SOAP 1.1) or the
soap.fault->SOAP_ENV__Detail variable (SOAP 1.2).
Use option -j to omit.

*/
struct SOAP_ENV__Detail
{
    struct ns2__JMSException*            ns1__JMSException             ;
///< SOAP Fault element ""http://webservice.comm.ideais.sf.net":JMSException" part "JMSException"
    struct ns5__NamingException*         ns1__NamingException          ;
///< SOAP Fault element ""http://webservice.comm.ideais.sf.net":NamingException" part "NamingException"
    int                                  __type                        ;	///< set to SOAP_TYPE_X for a serializable type X
    void                                *fault                         ;	///< points to serializable object X or NULL
    _XML                                 __any                         ;	///< Catch any element content in XML string.
};

/******************************************************************************\
 *                                                                            *
 * JMSServiceHttpBinding                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __ns1__getMsgFromTopic                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getMsgFromTopic" of service binding "JMSServiceHttpBinding"

/**

Operation details:

  - SOAP document/literal style
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":JMSException (literal)
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":NamingException (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getMsgFromTopic(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__getMsgFromTopic*       ns1__getMsgFromTopic,
    // response parameters:
    struct _ns1__getMsgFromTopicResponse* ns1__getMsgFromTopicResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getMsgFromTopic(
    struct soap *soap,
    // request parameters:
    struct _ns1__getMsgFromTopic*       ns1__getMsgFromTopic,
    // response parameters:
    struct _ns1__getMsgFromTopicResponse* ns1__getMsgFromTopicResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	getMsgFromTopic document
//gsoap ns1  service method-encoding:	getMsgFromTopic literal
//gsoap ns1  service method-action:	getMsgFromTopic ""
//gsoap ns1  service method-fault:	getMsgFromTopic ns1__JMSException
//gsoap ns1  service method-fault:	getMsgFromTopic ns1__NamingException
int __ns1__getMsgFromTopic(
    struct _ns1__getMsgFromTopic*       ns1__getMsgFromTopic,	///< Request parameter
    struct _ns1__getMsgFromTopicResponse* ns1__getMsgFromTopicResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __ns1__postMsgToTopic                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__postMsgToTopic" of service binding "JMSServiceHttpBinding"

/**

Operation details:

  - SOAP document/literal style
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":JMSException (literal)
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":NamingException (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__postMsgToTopic(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__postMsgToTopic*        ns1__postMsgToTopic,
    // response parameters:
    struct _ns1__postMsgToTopicResponse* ns1__postMsgToTopicResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__postMsgToTopic(
    struct soap *soap,
    // request parameters:
    struct _ns1__postMsgToTopic*        ns1__postMsgToTopic,
    // response parameters:
    struct _ns1__postMsgToTopicResponse* ns1__postMsgToTopicResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	postMsgToTopic document
//gsoap ns1  service method-encoding:	postMsgToTopic literal
//gsoap ns1  service method-action:	postMsgToTopic ""
//gsoap ns1  service method-fault:	postMsgToTopic ns1__JMSException
//gsoap ns1  service method-fault:	postMsgToTopic ns1__NamingException
int __ns1__postMsgToTopic(
    struct _ns1__postMsgToTopic*        ns1__postMsgToTopic,	///< Request parameter
    struct _ns1__postMsgToTopicResponse* ns1__postMsgToTopicResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __ns1__postMsgToQueue                                                      *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__postMsgToQueue" of service binding "JMSServiceHttpBinding"

/**

Operation details:

  - SOAP document/literal style
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":JMSException (literal)
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":NamingException (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__postMsgToQueue(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__postMsgToQueue*        ns1__postMsgToQueue,
    // response parameters:
    struct _ns1__postMsgToQueueResponse* ns1__postMsgToQueueResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__postMsgToQueue(
    struct soap *soap,
    // request parameters:
    struct _ns1__postMsgToQueue*        ns1__postMsgToQueue,
    // response parameters:
    struct _ns1__postMsgToQueueResponse* ns1__postMsgToQueueResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	postMsgToQueue document
//gsoap ns1  service method-encoding:	postMsgToQueue literal
//gsoap ns1  service method-action:	postMsgToQueue ""
//gsoap ns1  service method-fault:	postMsgToQueue ns1__JMSException
//gsoap ns1  service method-fault:	postMsgToQueue ns1__NamingException
int __ns1__postMsgToQueue(
    struct _ns1__postMsgToQueue*        ns1__postMsgToQueue,	///< Request parameter
    struct _ns1__postMsgToQueueResponse* ns1__postMsgToQueueResponse	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * __ns1__getMsgFromQueue                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getMsgFromQueue" of service binding "JMSServiceHttpBinding"

/**

Operation details:

  - SOAP document/literal style
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":JMSException (literal)
  - SOAP Fault: "http://webservice.comm.ideais.sf.net":NamingException (literal)

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getMsgFromQueue(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__getMsgFromQueue*       ns1__getMsgFromQueue,
    // response parameters:
    struct _ns1__getMsgFromQueueResponse* ns1__getMsgFromQueueResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getMsgFromQueue(
    struct soap *soap,
    // request parameters:
    struct _ns1__getMsgFromQueue*       ns1__getMsgFromQueue,
    // response parameters:
    struct _ns1__getMsgFromQueueResponse* ns1__getMsgFromQueueResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	getMsgFromQueue document
//gsoap ns1  service method-encoding:	getMsgFromQueue literal
//gsoap ns1  service method-action:	getMsgFromQueue ""
//gsoap ns1  service method-fault:	getMsgFromQueue ns1__JMSException
//gsoap ns1  service method-fault:	getMsgFromQueue ns1__NamingException
int __ns1__getMsgFromQueue(
    struct _ns1__getMsgFromQueue*       ns1__getMsgFromQueue,	///< Request parameter
    struct _ns1__getMsgFromQueueResponse* ns1__getMsgFromQueueResponse	///< Response parameter
);

/* End of ws/jms2webservice.h */
