/* soapH.h
   Generated by gSOAP 2.7.9e from ws/jms2webservice.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE___ns1__getMsgFromQueue
#define SOAP_TYPE___ns1__getMsgFromQueue (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getMsgFromQueue(struct soap*, struct __ns1__getMsgFromQueue *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getMsgFromQueue(struct soap*, const struct __ns1__getMsgFromQueue *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getMsgFromQueue(struct soap*, const struct __ns1__getMsgFromQueue *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getMsgFromQueue(struct soap*, const char*, int, const struct __ns1__getMsgFromQueue *, const char*);
SOAP_FMAC3 struct __ns1__getMsgFromQueue * SOAP_FMAC4 soap_get___ns1__getMsgFromQueue(struct soap*, struct __ns1__getMsgFromQueue *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getMsgFromQueue * SOAP_FMAC4 soap_in___ns1__getMsgFromQueue(struct soap*, const char*, struct __ns1__getMsgFromQueue *, const char*);

#ifndef SOAP_TYPE___ns1__postMsgToQueue
#define SOAP_TYPE___ns1__postMsgToQueue (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__postMsgToQueue(struct soap*, struct __ns1__postMsgToQueue *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__postMsgToQueue(struct soap*, const struct __ns1__postMsgToQueue *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__postMsgToQueue(struct soap*, const struct __ns1__postMsgToQueue *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__postMsgToQueue(struct soap*, const char*, int, const struct __ns1__postMsgToQueue *, const char*);
SOAP_FMAC3 struct __ns1__postMsgToQueue * SOAP_FMAC4 soap_get___ns1__postMsgToQueue(struct soap*, struct __ns1__postMsgToQueue *, const char*, const char*);
SOAP_FMAC3 struct __ns1__postMsgToQueue * SOAP_FMAC4 soap_in___ns1__postMsgToQueue(struct soap*, const char*, struct __ns1__postMsgToQueue *, const char*);

#ifndef SOAP_TYPE___ns1__postMsgToTopic
#define SOAP_TYPE___ns1__postMsgToTopic (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__postMsgToTopic(struct soap*, struct __ns1__postMsgToTopic *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__postMsgToTopic(struct soap*, const struct __ns1__postMsgToTopic *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__postMsgToTopic(struct soap*, const struct __ns1__postMsgToTopic *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__postMsgToTopic(struct soap*, const char*, int, const struct __ns1__postMsgToTopic *, const char*);
SOAP_FMAC3 struct __ns1__postMsgToTopic * SOAP_FMAC4 soap_get___ns1__postMsgToTopic(struct soap*, struct __ns1__postMsgToTopic *, const char*, const char*);
SOAP_FMAC3 struct __ns1__postMsgToTopic * SOAP_FMAC4 soap_in___ns1__postMsgToTopic(struct soap*, const char*, struct __ns1__postMsgToTopic *, const char*);

#ifndef SOAP_TYPE___ns1__getMsgFromTopic
#define SOAP_TYPE___ns1__getMsgFromTopic (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getMsgFromTopic(struct soap*, struct __ns1__getMsgFromTopic *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getMsgFromTopic(struct soap*, const struct __ns1__getMsgFromTopic *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getMsgFromTopic(struct soap*, const struct __ns1__getMsgFromTopic *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getMsgFromTopic(struct soap*, const char*, int, const struct __ns1__getMsgFromTopic *, const char*);
SOAP_FMAC3 struct __ns1__getMsgFromTopic * SOAP_FMAC4 soap_get___ns1__getMsgFromTopic(struct soap*, struct __ns1__getMsgFromTopic *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getMsgFromTopic * SOAP_FMAC4 soap_in___ns1__getMsgFromTopic(struct soap*, const char*, struct __ns1__getMsgFromTopic *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef SOAP_TYPE_ns5__Name
#define SOAP_TYPE_ns5__Name (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__Name(struct soap*, struct ns5__Name *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__Name(struct soap*, const struct ns5__Name *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__Name(struct soap*, const struct ns5__Name *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__Name(struct soap*, const char*, int, const struct ns5__Name *, const char*);
SOAP_FMAC3 struct ns5__Name * SOAP_FMAC4 soap_get_ns5__Name(struct soap*, struct ns5__Name *, const char*, const char*);
SOAP_FMAC3 struct ns5__Name * SOAP_FMAC4 soap_in_ns5__Name(struct soap*, const char*, struct ns5__Name *, const char*);

#ifndef SOAP_TYPE_ns5__NamingException
#define SOAP_TYPE_ns5__NamingException (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__NamingException(struct soap*, struct ns5__NamingException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__NamingException(struct soap*, const struct ns5__NamingException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__NamingException(struct soap*, const struct ns5__NamingException *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__NamingException(struct soap*, const char*, int, const struct ns5__NamingException *, const char*);
SOAP_FMAC3 struct ns5__NamingException * SOAP_FMAC4 soap_get_ns5__NamingException(struct soap*, struct ns5__NamingException *, const char*, const char*);
SOAP_FMAC3 struct ns5__NamingException * SOAP_FMAC4 soap_in_ns5__NamingException(struct soap*, const char*, struct ns5__NamingException *, const char*);

#ifndef SOAP_TYPE_ns4__Throwable
#define SOAP_TYPE_ns4__Throwable (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__Throwable(struct soap*, struct ns4__Throwable *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__Throwable(struct soap*, const struct ns4__Throwable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__Throwable(struct soap*, const struct ns4__Throwable *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__Throwable(struct soap*, const char*, int, const struct ns4__Throwable *, const char*);
SOAP_FMAC3 struct ns4__Throwable * SOAP_FMAC4 soap_get_ns4__Throwable(struct soap*, struct ns4__Throwable *, const char*, const char*);
SOAP_FMAC3 struct ns4__Throwable * SOAP_FMAC4 soap_in_ns4__Throwable(struct soap*, const char*, struct ns4__Throwable *, const char*);

#ifndef SOAP_TYPE_ns4__Exception
#define SOAP_TYPE_ns4__Exception (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__Exception(struct soap*, struct ns4__Exception *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__Exception(struct soap*, const struct ns4__Exception *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__Exception(struct soap*, const struct ns4__Exception *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__Exception(struct soap*, const char*, int, const struct ns4__Exception *, const char*);
SOAP_FMAC3 struct ns4__Exception * SOAP_FMAC4 soap_get_ns4__Exception(struct soap*, struct ns4__Exception *, const char*, const char*);
SOAP_FMAC3 struct ns4__Exception * SOAP_FMAC4 soap_in_ns4__Exception(struct soap*, const char*, struct ns4__Exception *, const char*);

#ifndef SOAP_TYPE_ns2__JMSException
#define SOAP_TYPE_ns2__JMSException (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__JMSException(struct soap*, struct ns2__JMSException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__JMSException(struct soap*, const struct ns2__JMSException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__JMSException(struct soap*, const struct ns2__JMSException *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__JMSException(struct soap*, const char*, int, const struct ns2__JMSException *, const char*);
SOAP_FMAC3 struct ns2__JMSException * SOAP_FMAC4 soap_get_ns2__JMSException(struct soap*, struct ns2__JMSException *, const char*, const char*);
SOAP_FMAC3 struct ns2__JMSException * SOAP_FMAC4 soap_in_ns2__JMSException(struct soap*, const char*, struct ns2__JMSException *, const char*);

#ifndef SOAP_TYPE_ns3__Enumeration
#define SOAP_TYPE_ns3__Enumeration (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__Enumeration(struct soap*, struct ns3__Enumeration *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__Enumeration(struct soap*, const struct ns3__Enumeration *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__Enumeration(struct soap*, const struct ns3__Enumeration *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Enumeration(struct soap*, const char*, int, const struct ns3__Enumeration *, const char*);
SOAP_FMAC3 struct ns3__Enumeration * SOAP_FMAC4 soap_get_ns3__Enumeration(struct soap*, struct ns3__Enumeration *, const char*, const char*);
SOAP_FMAC3 struct ns3__Enumeration * SOAP_FMAC4 soap_in_ns3__Enumeration(struct soap*, const char*, struct ns3__Enumeration *, const char*);

#ifndef SOAP_TYPE_ns2__Destination
#define SOAP_TYPE_ns2__Destination (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__Destination(struct soap*, struct ns2__Destination *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__Destination(struct soap*, const struct ns2__Destination *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__Destination(struct soap*, const struct ns2__Destination *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__Destination(struct soap*, const char*, int, const struct ns2__Destination *, const char*);
SOAP_FMAC3 struct ns2__Destination * SOAP_FMAC4 soap_get_ns2__Destination(struct soap*, struct ns2__Destination *, const char*, const char*);
SOAP_FMAC3 struct ns2__Destination * SOAP_FMAC4 soap_in_ns2__Destination(struct soap*, const char*, struct ns2__Destination *, const char*);

#ifndef SOAP_TYPE__ns1__getMsgFromQueueResponse
#define SOAP_TYPE__ns1__getMsgFromQueueResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getMsgFromQueueResponse(struct soap*, struct _ns1__getMsgFromQueueResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getMsgFromQueueResponse(struct soap*, const struct _ns1__getMsgFromQueueResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getMsgFromQueueResponse(struct soap*, const struct _ns1__getMsgFromQueueResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getMsgFromQueueResponse(struct soap*, const char*, int, const struct _ns1__getMsgFromQueueResponse *, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueueResponse * SOAP_FMAC4 soap_get__ns1__getMsgFromQueueResponse(struct soap*, struct _ns1__getMsgFromQueueResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueueResponse * SOAP_FMAC4 soap_in__ns1__getMsgFromQueueResponse(struct soap*, const char*, struct _ns1__getMsgFromQueueResponse *, const char*);

#ifndef SOAP_TYPE__ns1__getMsgFromQueue
#define SOAP_TYPE__ns1__getMsgFromQueue (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getMsgFromQueue(struct soap*, struct _ns1__getMsgFromQueue *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getMsgFromQueue(struct soap*, const struct _ns1__getMsgFromQueue *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getMsgFromQueue(struct soap*, const struct _ns1__getMsgFromQueue *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getMsgFromQueue(struct soap*, const char*, int, const struct _ns1__getMsgFromQueue *, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueue * SOAP_FMAC4 soap_get__ns1__getMsgFromQueue(struct soap*, struct _ns1__getMsgFromQueue *, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueue * SOAP_FMAC4 soap_in__ns1__getMsgFromQueue(struct soap*, const char*, struct _ns1__getMsgFromQueue *, const char*);

#ifndef SOAP_TYPE__ns1__postMsgToQueueResponse
#define SOAP_TYPE__ns1__postMsgToQueueResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__postMsgToQueueResponse(struct soap*, struct _ns1__postMsgToQueueResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__postMsgToQueueResponse(struct soap*, const struct _ns1__postMsgToQueueResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__postMsgToQueueResponse(struct soap*, const struct _ns1__postMsgToQueueResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__postMsgToQueueResponse(struct soap*, const char*, int, const struct _ns1__postMsgToQueueResponse *, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueueResponse * SOAP_FMAC4 soap_get__ns1__postMsgToQueueResponse(struct soap*, struct _ns1__postMsgToQueueResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueueResponse * SOAP_FMAC4 soap_in__ns1__postMsgToQueueResponse(struct soap*, const char*, struct _ns1__postMsgToQueueResponse *, const char*);

#ifndef SOAP_TYPE__ns1__postMsgToQueue
#define SOAP_TYPE__ns1__postMsgToQueue (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__postMsgToQueue(struct soap*, struct _ns1__postMsgToQueue *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__postMsgToQueue(struct soap*, const struct _ns1__postMsgToQueue *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__postMsgToQueue(struct soap*, const struct _ns1__postMsgToQueue *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__postMsgToQueue(struct soap*, const char*, int, const struct _ns1__postMsgToQueue *, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueue * SOAP_FMAC4 soap_get__ns1__postMsgToQueue(struct soap*, struct _ns1__postMsgToQueue *, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueue * SOAP_FMAC4 soap_in__ns1__postMsgToQueue(struct soap*, const char*, struct _ns1__postMsgToQueue *, const char*);

#ifndef SOAP_TYPE_ns2__TextMessage
#define SOAP_TYPE_ns2__TextMessage (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__TextMessage(struct soap*, struct ns2__TextMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__TextMessage(struct soap*, const struct ns2__TextMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__TextMessage(struct soap*, const struct ns2__TextMessage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__TextMessage(struct soap*, const char*, int, const struct ns2__TextMessage *, const char*);
SOAP_FMAC3 struct ns2__TextMessage * SOAP_FMAC4 soap_get_ns2__TextMessage(struct soap*, struct ns2__TextMessage *, const char*, const char*);
SOAP_FMAC3 struct ns2__TextMessage * SOAP_FMAC4 soap_in_ns2__TextMessage(struct soap*, const char*, struct ns2__TextMessage *, const char*);

#ifndef SOAP_TYPE__ns1__postMsgToTopicResponse
#define SOAP_TYPE__ns1__postMsgToTopicResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__postMsgToTopicResponse(struct soap*, struct _ns1__postMsgToTopicResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__postMsgToTopicResponse(struct soap*, const struct _ns1__postMsgToTopicResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__postMsgToTopicResponse(struct soap*, const struct _ns1__postMsgToTopicResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__postMsgToTopicResponse(struct soap*, const char*, int, const struct _ns1__postMsgToTopicResponse *, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopicResponse * SOAP_FMAC4 soap_get__ns1__postMsgToTopicResponse(struct soap*, struct _ns1__postMsgToTopicResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopicResponse * SOAP_FMAC4 soap_in__ns1__postMsgToTopicResponse(struct soap*, const char*, struct _ns1__postMsgToTopicResponse *, const char*);

#ifndef SOAP_TYPE__ns1__postMsgToTopic
#define SOAP_TYPE__ns1__postMsgToTopic (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__postMsgToTopic(struct soap*, struct _ns1__postMsgToTopic *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__postMsgToTopic(struct soap*, const struct _ns1__postMsgToTopic *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__postMsgToTopic(struct soap*, const struct _ns1__postMsgToTopic *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__postMsgToTopic(struct soap*, const char*, int, const struct _ns1__postMsgToTopic *, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopic * SOAP_FMAC4 soap_get__ns1__postMsgToTopic(struct soap*, struct _ns1__postMsgToTopic *, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopic * SOAP_FMAC4 soap_in__ns1__postMsgToTopic(struct soap*, const char*, struct _ns1__postMsgToTopic *, const char*);

#ifndef SOAP_TYPE_ns2__ArrayOfTextMessage
#define SOAP_TYPE_ns2__ArrayOfTextMessage (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ArrayOfTextMessage(struct soap*, struct ns2__ArrayOfTextMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ArrayOfTextMessage(struct soap*, const struct ns2__ArrayOfTextMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ArrayOfTextMessage(struct soap*, const struct ns2__ArrayOfTextMessage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ArrayOfTextMessage(struct soap*, const char*, int, const struct ns2__ArrayOfTextMessage *, const char*);
SOAP_FMAC3 struct ns2__ArrayOfTextMessage * SOAP_FMAC4 soap_get_ns2__ArrayOfTextMessage(struct soap*, struct ns2__ArrayOfTextMessage *, const char*, const char*);
SOAP_FMAC3 struct ns2__ArrayOfTextMessage * SOAP_FMAC4 soap_in_ns2__ArrayOfTextMessage(struct soap*, const char*, struct ns2__ArrayOfTextMessage *, const char*);

#ifndef SOAP_TYPE__ns1__getMsgFromTopicResponse
#define SOAP_TYPE__ns1__getMsgFromTopicResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getMsgFromTopicResponse(struct soap*, struct _ns1__getMsgFromTopicResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getMsgFromTopicResponse(struct soap*, const struct _ns1__getMsgFromTopicResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getMsgFromTopicResponse(struct soap*, const struct _ns1__getMsgFromTopicResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getMsgFromTopicResponse(struct soap*, const char*, int, const struct _ns1__getMsgFromTopicResponse *, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopicResponse * SOAP_FMAC4 soap_get__ns1__getMsgFromTopicResponse(struct soap*, struct _ns1__getMsgFromTopicResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopicResponse * SOAP_FMAC4 soap_in__ns1__getMsgFromTopicResponse(struct soap*, const char*, struct _ns1__getMsgFromTopicResponse *, const char*);

#ifndef SOAP_TYPE__ns1__getMsgFromTopic
#define SOAP_TYPE__ns1__getMsgFromTopic (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getMsgFromTopic(struct soap*, struct _ns1__getMsgFromTopic *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getMsgFromTopic(struct soap*, const struct _ns1__getMsgFromTopic *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getMsgFromTopic(struct soap*, const struct _ns1__getMsgFromTopic *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getMsgFromTopic(struct soap*, const char*, int, const struct _ns1__getMsgFromTopic *, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopic * SOAP_FMAC4 soap_get__ns1__getMsgFromTopic(struct soap*, struct _ns1__getMsgFromTopic *, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopic * SOAP_FMAC4 soap_in__ns1__getMsgFromTopic(struct soap*, const char*, struct _ns1__getMsgFromTopic *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__getMsgFromQueueResponse
#define SOAP_TYPE_PointerTo_ns1__getMsgFromQueueResponse (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getMsgFromQueueResponse(struct soap*, struct _ns1__getMsgFromQueueResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getMsgFromQueueResponse(struct soap*, struct _ns1__getMsgFromQueueResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getMsgFromQueueResponse(struct soap*, const char *, int, struct _ns1__getMsgFromQueueResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__getMsgFromQueueResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getMsgFromQueueResponse(struct soap*, struct _ns1__getMsgFromQueueResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueueResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getMsgFromQueueResponse(struct soap*, const char*, struct _ns1__getMsgFromQueueResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getMsgFromQueue
#define SOAP_TYPE_PointerTo_ns1__getMsgFromQueue (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getMsgFromQueue(struct soap*, struct _ns1__getMsgFromQueue *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getMsgFromQueue(struct soap*, struct _ns1__getMsgFromQueue *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getMsgFromQueue(struct soap*, const char *, int, struct _ns1__getMsgFromQueue *const*, const char *);
SOAP_FMAC3 struct _ns1__getMsgFromQueue ** SOAP_FMAC4 soap_get_PointerTo_ns1__getMsgFromQueue(struct soap*, struct _ns1__getMsgFromQueue **, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromQueue ** SOAP_FMAC4 soap_in_PointerTo_ns1__getMsgFromQueue(struct soap*, const char*, struct _ns1__getMsgFromQueue **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__postMsgToQueueResponse
#define SOAP_TYPE_PointerTo_ns1__postMsgToQueueResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__postMsgToQueueResponse(struct soap*, struct _ns1__postMsgToQueueResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__postMsgToQueueResponse(struct soap*, struct _ns1__postMsgToQueueResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__postMsgToQueueResponse(struct soap*, const char *, int, struct _ns1__postMsgToQueueResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__postMsgToQueueResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__postMsgToQueueResponse(struct soap*, struct _ns1__postMsgToQueueResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueueResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__postMsgToQueueResponse(struct soap*, const char*, struct _ns1__postMsgToQueueResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__postMsgToQueue
#define SOAP_TYPE_PointerTo_ns1__postMsgToQueue (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__postMsgToQueue(struct soap*, struct _ns1__postMsgToQueue *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__postMsgToQueue(struct soap*, struct _ns1__postMsgToQueue *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__postMsgToQueue(struct soap*, const char *, int, struct _ns1__postMsgToQueue *const*, const char *);
SOAP_FMAC3 struct _ns1__postMsgToQueue ** SOAP_FMAC4 soap_get_PointerTo_ns1__postMsgToQueue(struct soap*, struct _ns1__postMsgToQueue **, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToQueue ** SOAP_FMAC4 soap_in_PointerTo_ns1__postMsgToQueue(struct soap*, const char*, struct _ns1__postMsgToQueue **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__postMsgToTopicResponse
#define SOAP_TYPE_PointerTo_ns1__postMsgToTopicResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__postMsgToTopicResponse(struct soap*, struct _ns1__postMsgToTopicResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__postMsgToTopicResponse(struct soap*, struct _ns1__postMsgToTopicResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__postMsgToTopicResponse(struct soap*, const char *, int, struct _ns1__postMsgToTopicResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__postMsgToTopicResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__postMsgToTopicResponse(struct soap*, struct _ns1__postMsgToTopicResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopicResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__postMsgToTopicResponse(struct soap*, const char*, struct _ns1__postMsgToTopicResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__postMsgToTopic
#define SOAP_TYPE_PointerTo_ns1__postMsgToTopic (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__postMsgToTopic(struct soap*, struct _ns1__postMsgToTopic *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__postMsgToTopic(struct soap*, struct _ns1__postMsgToTopic *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__postMsgToTopic(struct soap*, const char *, int, struct _ns1__postMsgToTopic *const*, const char *);
SOAP_FMAC3 struct _ns1__postMsgToTopic ** SOAP_FMAC4 soap_get_PointerTo_ns1__postMsgToTopic(struct soap*, struct _ns1__postMsgToTopic **, const char*, const char*);
SOAP_FMAC3 struct _ns1__postMsgToTopic ** SOAP_FMAC4 soap_in_PointerTo_ns1__postMsgToTopic(struct soap*, const char*, struct _ns1__postMsgToTopic **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getMsgFromTopicResponse
#define SOAP_TYPE_PointerTo_ns1__getMsgFromTopicResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getMsgFromTopicResponse(struct soap*, struct _ns1__getMsgFromTopicResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getMsgFromTopicResponse(struct soap*, struct _ns1__getMsgFromTopicResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getMsgFromTopicResponse(struct soap*, const char *, int, struct _ns1__getMsgFromTopicResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__getMsgFromTopicResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getMsgFromTopicResponse(struct soap*, struct _ns1__getMsgFromTopicResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopicResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getMsgFromTopicResponse(struct soap*, const char*, struct _ns1__getMsgFromTopicResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getMsgFromTopic
#define SOAP_TYPE_PointerTo_ns1__getMsgFromTopic (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getMsgFromTopic(struct soap*, struct _ns1__getMsgFromTopic *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getMsgFromTopic(struct soap*, struct _ns1__getMsgFromTopic *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getMsgFromTopic(struct soap*, const char *, int, struct _ns1__getMsgFromTopic *const*, const char *);
SOAP_FMAC3 struct _ns1__getMsgFromTopic ** SOAP_FMAC4 soap_get_PointerTo_ns1__getMsgFromTopic(struct soap*, struct _ns1__getMsgFromTopic **, const char*, const char*);
SOAP_FMAC3 struct _ns1__getMsgFromTopic ** SOAP_FMAC4 soap_in_PointerTo_ns1__getMsgFromTopic(struct soap*, const char*, struct _ns1__getMsgFromTopic **, const char*);

#ifndef SOAP_TYPE_PointerTons5__NamingException
#define SOAP_TYPE_PointerTons5__NamingException (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__NamingException(struct soap*, struct ns5__NamingException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__NamingException(struct soap*, struct ns5__NamingException *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__NamingException(struct soap*, const char *, int, struct ns5__NamingException *const*, const char *);
SOAP_FMAC3 struct ns5__NamingException ** SOAP_FMAC4 soap_get_PointerTons5__NamingException(struct soap*, struct ns5__NamingException **, const char*, const char*);
SOAP_FMAC3 struct ns5__NamingException ** SOAP_FMAC4 soap_in_PointerTons5__NamingException(struct soap*, const char*, struct ns5__NamingException **, const char*);

#ifndef SOAP_TYPE_PointerTons2__JMSException
#define SOAP_TYPE_PointerTons2__JMSException (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__JMSException(struct soap*, struct ns2__JMSException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__JMSException(struct soap*, struct ns2__JMSException *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__JMSException(struct soap*, const char *, int, struct ns2__JMSException *const*, const char *);
SOAP_FMAC3 struct ns2__JMSException ** SOAP_FMAC4 soap_get_PointerTons2__JMSException(struct soap*, struct ns2__JMSException **, const char*, const char*);
SOAP_FMAC3 struct ns2__JMSException ** SOAP_FMAC4 soap_in_PointerTons2__JMSException(struct soap*, const char*, struct ns2__JMSException **, const char*);

#ifndef SOAP_TYPE_PointerTons5__Name
#define SOAP_TYPE_PointerTons5__Name (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__Name(struct soap*, struct ns5__Name *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__Name(struct soap*, struct ns5__Name *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__Name(struct soap*, const char *, int, struct ns5__Name *const*, const char *);
SOAP_FMAC3 struct ns5__Name ** SOAP_FMAC4 soap_get_PointerTons5__Name(struct soap*, struct ns5__Name **, const char*, const char*);
SOAP_FMAC3 struct ns5__Name ** SOAP_FMAC4 soap_in_PointerTons5__Name(struct soap*, const char*, struct ns5__Name **, const char*);

#ifndef SOAP_TYPE_PointerTons4__Throwable
#define SOAP_TYPE_PointerTons4__Throwable (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__Throwable(struct soap*, struct ns4__Throwable *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__Throwable(struct soap*, struct ns4__Throwable *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__Throwable(struct soap*, const char *, int, struct ns4__Throwable *const*, const char *);
SOAP_FMAC3 struct ns4__Throwable ** SOAP_FMAC4 soap_get_PointerTons4__Throwable(struct soap*, struct ns4__Throwable **, const char*, const char*);
SOAP_FMAC3 struct ns4__Throwable ** SOAP_FMAC4 soap_in_PointerTons4__Throwable(struct soap*, const char*, struct ns4__Throwable **, const char*);

#ifndef SOAP_TYPE_PointerTons4__Exception
#define SOAP_TYPE_PointerTons4__Exception (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__Exception(struct soap*, struct ns4__Exception *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__Exception(struct soap*, struct ns4__Exception *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__Exception(struct soap*, const char *, int, struct ns4__Exception *const*, const char *);
SOAP_FMAC3 struct ns4__Exception ** SOAP_FMAC4 soap_get_PointerTons4__Exception(struct soap*, struct ns4__Exception **, const char*, const char*);
SOAP_FMAC3 struct ns4__Exception ** SOAP_FMAC4 soap_in_PointerTons4__Exception(struct soap*, const char*, struct ns4__Exception **, const char*);

#ifndef SOAP_TYPE_PointerTons3__Enumeration
#define SOAP_TYPE_PointerTons3__Enumeration (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__Enumeration(struct soap*, struct ns3__Enumeration *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__Enumeration(struct soap*, struct ns3__Enumeration *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__Enumeration(struct soap*, const char *, int, struct ns3__Enumeration *const*, const char *);
SOAP_FMAC3 struct ns3__Enumeration ** SOAP_FMAC4 soap_get_PointerTons3__Enumeration(struct soap*, struct ns3__Enumeration **, const char*, const char*);
SOAP_FMAC3 struct ns3__Enumeration ** SOAP_FMAC4 soap_in_PointerTons3__Enumeration(struct soap*, const char*, struct ns3__Enumeration **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);

#ifndef SOAP_TYPE_PointerToLONG64
#define SOAP_TYPE_PointerToLONG64 (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToLONG64(struct soap*, LONG64 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToLONG64(struct soap*, LONG64 *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToLONG64(struct soap*, const char *, int, LONG64 *const*, const char *);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_get_PointerToLONG64(struct soap*, LONG64 **, const char*, const char*);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_in_PointerToLONG64(struct soap*, const char*, LONG64 **, const char*);

#ifndef SOAP_TYPE_PointerTons2__Destination
#define SOAP_TYPE_PointerTons2__Destination (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__Destination(struct soap*, struct ns2__Destination *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__Destination(struct soap*, struct ns2__Destination *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__Destination(struct soap*, const char *, int, struct ns2__Destination *const*, const char *);
SOAP_FMAC3 struct ns2__Destination ** SOAP_FMAC4 soap_get_PointerTons2__Destination(struct soap*, struct ns2__Destination **, const char*, const char*);
SOAP_FMAC3 struct ns2__Destination ** SOAP_FMAC4 soap_in_PointerTons2__Destination(struct soap*, const char*, struct ns2__Destination **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, struct xsd__base64Binary *const*, const char *);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary **, const char*);

#ifndef SOAP_TYPE_PointerTons2__TextMessage
#define SOAP_TYPE_PointerTons2__TextMessage (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__TextMessage(struct soap*, struct ns2__TextMessage *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__TextMessage(struct soap*, struct ns2__TextMessage *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__TextMessage(struct soap*, const char *, int, struct ns2__TextMessage *const*, const char *);
SOAP_FMAC3 struct ns2__TextMessage ** SOAP_FMAC4 soap_get_PointerTons2__TextMessage(struct soap*, struct ns2__TextMessage **, const char*, const char*);
SOAP_FMAC3 struct ns2__TextMessage ** SOAP_FMAC4 soap_in_PointerTons2__TextMessage(struct soap*, const char*, struct ns2__TextMessage **, const char*);

#ifndef SOAP_TYPE_PointerTons2__ArrayOfTextMessage
#define SOAP_TYPE_PointerTons2__ArrayOfTextMessage (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ArrayOfTextMessage(struct soap*, struct ns2__ArrayOfTextMessage *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ArrayOfTextMessage(struct soap*, struct ns2__ArrayOfTextMessage *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ArrayOfTextMessage(struct soap*, const char *, int, struct ns2__ArrayOfTextMessage *const*, const char *);
SOAP_FMAC3 struct ns2__ArrayOfTextMessage ** SOAP_FMAC4 soap_get_PointerTons2__ArrayOfTextMessage(struct soap*, struct ns2__ArrayOfTextMessage **, const char*, const char*);
SOAP_FMAC3 struct ns2__ArrayOfTextMessage ** SOAP_FMAC4 soap_in_PointerTons2__ArrayOfTextMessage(struct soap*, const char*, struct ns2__ArrayOfTextMessage **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
